Repository Sima-J/KFD, pull requests merged in 2021-06, with the labels that each got.

#55 User card Finalized
  src/assets/ProfileIcon.png
  src/components/DonationInfo/DonationContact.jsx
  src/components/DonationInfo/DonationContact.scss
  src/components/DonationInfo/DonationSection.jsx
  src/containers/DonationDetails/DonationDetails.jsx
Labels: Feat

#56 My Donations Finished
  src/components/ProfileCard/ProfileCard.jsx
  src/components/ProfileCard/ProfileCard.scss
Labels: Feat

#57 Add donation
  package-lock.json
Labels: Feat

#59 Google Authentication is Implemented Successfully. Note/ i'll fix the Module Design later
  package-lock.json
  package.json
  src/assets/login/bg-modal.svg
  src/assets/login/close.svg
  src/assets/login/facebook.svg
  src/assets/login/google.svg
  src/components/MainNavbar/MainNavbar.jsx
  src/components/Modals/Login.css
  src/components/Modals/Login.jsx
  src/i18n.js
  src/index.js
  src/locales/ar.json
  src/locales/en.json
  src/locales/kr.json
  src/redux/actions/actions.js
  src/redux/actions/user.js
  src/redux/comments/reducer.js
  src/redux/reducers/AllReducers.js
  src/redux/reducers/petReducer.js
  src/redux/reducers/user.js
  src/redux/store.js
  src/redux/types.js
Labels: Feat

#63 Web translation
  package-lock.json
  package.json
  src/components/AboutUs/AboutUs.jsx
Labels: Feat

#65 Login Module Updated
  src/assets/login/bg-modal.svg
  src/assets/login/bg-modal1.svg
  src/assets/login/bg-modal3.svg
  src/assets/login/bg-modal4.svg
Labels: Feat

#66 Filtering added and finalized
  package-lock.json
  package.json
  src/components/FliterOption/FilterOptions.scss
  src/components/FliterOption/FliterOption.jsx
  src/containers/AddDonation/AddDonation.jsx
  src/containers/AddDonation/AddDonation.scss
  src/containers/Search/Search.jsx
Labels: Feat

#68 Translation
  src/locales/ar.json
  src/locales/en.json
  src/locales/kr.json
Labels: Doc

#70 Bug fixes
  src/components/Modals/Login.scss
  src/components/ProfileCard/ProfileCard.jsx
  src/components/SearchForm/SearchHeader.jsx
Labels: Fix

#71 Bug fix
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/Modals/Login.css
  src/components/Modals/Login.jsx
Labels: Fix

#76 Nav bar hidden
  src/App.js
  src/components/MainNavbar/MainNavbar.jsx
  src/components/ProfileCard/ProfileCard.jsx
  src/containers/NotFound/NotFound.jsx
  src/containers/Profile/Profile.jsx
  src/privateroutes.jsx
Labels: Feat

#77 Feat: Private routes
  src/App.js
Labels: Feat, Fix

#79 Private routes
  package-lock.json
  package.json
  src/App.js
  src/containers/NotFound/NotFound.jsx
  src/privateroutes.jsx
Labels: Feat, Fix

#80 Nav bar hidden
  src/components/Footer/Footer.jsx
  src/components/HomeCard/Header.jsx
Labels: Fix

#82 Tab bar
  public/favicon.ico
  public/index.html
  public/logo.png
  public/logo.svg
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: Fix

#83 Update AddDonationForm.jsx
  src/components/AddDonationForm/AddDonationForm.jsx
Labels: Fix

#84 Update ProfileCard.jsx
  src/components/ProfileCard/ProfileCard.jsx
Labels: Fix

#85 Update AddDonation.jsx
  src/containers/AddDonation/AddDonation.jsx
Labels: Fix

#90 Fixing the json File Eng only
  src/components/AboutUs/AboutUs.jsx
  src/components/AboutUs/AboutUs.scss
  src/components/AddDonationBtn/AddDonationBtn.jsx
  src/components/AddDonationForm/AddDonationForm.jsx
  src/components/CheckboxFilter/CheckboxFilter.jsx
  src/components/ContactForm/ContactFrom.jsx
  src/components/ContactInfoCard/ContactInfo.jsx
  src/components/DonationDetail/DonationDetail.jsx
  src/components/DonationsCarousal/Carousal.jsx
  src/components/FliterOption/FliterOption.jsx
  src/components/Footer/Footer.jsx
  src/components/MainNavbar/MainNavbar.jsx
  src/locales/en.json
Labels: Feat
